[{$smarty.block.parent}]
[{if $oViewConf->isActiveThemeFlow() || $oViewConf->isActiveThemeWave()}]
    [{assign var="flowErrorClass" value='flow-error' }]
[{else}]
    [{assign var="flowErrorClass" value='' }]
[{/if}]
[{assign var="iPayError" value=$oView->getPaymentError() }]
[{if $iPayError}]
    <div class="status error alert alert-danger [{$flowErrorClass}]">
        [{if $iPayError == -200}] [{* Payolution_Error::REJECTED *}]
                [{ oxmultilang ident="PAYOLUTION_ERROR_REQUEST_WAS_REJECTED_ON_PRECHECK" }]
        [{elseif $iPayError == -201}] [{* Payolution_Error::VALIDATION_REQUIRED_FIELDS_IS_MISSING *}]
                [{ oxmultilang ident="PAYOLUTION_ERROR_MISSING_REQUIRED_FIELDS" }]
        [{elseif $iPayError == -202}] [{* Payolution_Error::VALIDATION_AGE_RESTRICTION *}]
                [{ oxmultilang ident="PAYOLUTION_ERROR_AGE_RESTRICTION" }]
        [{elseif $iPayError == -203}] [{* Payolution_Error::VALIDATION_ADDRESS *}]
                [{ oxmultilang ident="PAYOLUTION_ERROR_ADDRESSES_IS_NOT_THE_SAME" }]
        [{elseif $iPayError == -204}] [{* Payolution_Error::VALIDATION_TERMS_AND_CONDITIONS *}]
                ident="PAYOLUTION_ERROR_TERMS_AND_CONDITIONS_HAS_NOT_AGREED" }]
        [{elseif $iPayError == -205}] [{* Payolution_Error::ORDER_STATUS_TRANSITION_NOT_ALLOWED *}]
                ident="PAYOLUTION_ERROR_ORDER_STATUS_TRANSITION_NOT_ALLOWED" }]
        [{elseif $iPayError == -206}] [{* Payolution_Error::PAYOLUTION_REMOTE_ERROR_RESPONSE *}]
                [{oxmultilang ident="PAYOLUTION_ERROR_REMOTE_ERROR_RESPONSE"}]
        [{/if}]
    </div>
[{/if}]